<a href="https://colab.research.google.com/github/dharalakshmi/dharalakshmi/blob/main/lab3_a9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Compute classification reports with zero_division parameter
report_train = classification_report(y_train, y_train_pred, zero_division=0, output_dict=True)
report_test = classification_report(y_test, y_test_pred, zero_division=0, output_dict=True)

# Print confusion matrices
print('Confusion Matrix (Training Set):')
print(confusion_matrix(y_train, y_train_pred))

print('\nConfusion Matrix (Test Set):')
print(confusion_matrix(y_test, y_test_pred))

# Print classification reports
print('\nClassification Report (Training Set):')
print(report_train)

print('\nClassification Report (Test Set):')
print(report_test)

# Compute precision, recall, and F1-score from reports
def extract_metrics(report):
    metrics = {
        'precision': {},
        'recall': {},
        'f1-score': {}
    }
    for label, metrics_dict in report.items():
        if label.isdigit():  # Only include numeric labels
            metrics['precision'][label] = metrics_dict['precision']
            metrics['recall'][label] = metrics_dict['recall']
            metrics['f1-score'][label] = metrics_dict['f1-score']
    return metrics

metrics_train = extract_metrics(report_train)
metrics_test = extract_metrics(report_test)

print('\nMetrics (Training Set):')
print('Precision:', metrics_train['precision'])
print('Recall:', metrics_train['recall'])
print('F1-Score:', metrics_train['f1-score'])

print('\nMetrics (Test Set):')
print('Precision:', metrics_test['precision'])
print('Recall:', metrics_test['recall'])
print('F1-Score:', metrics_test['f1-score'])

# Analyze for overfitting, underfitting, or regular fitting
def analyze_fit(train_acc, test_acc, train_f1, test_f1):
    if train_acc > test_acc and train_f1 > test_f1:
        print("The model is likely overfitting.")
    elif train_acc < test_acc and train_f1 < test_f1:
        print("The model is likely underfitting.")
    else:
        print("The model appears to be well-fit.")

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
train_f1 = np.mean(list(metrics_train['f1-score'].values()))
test_f1 = np.mean(list(metrics_test['f1-score'].values()))

print('\nTrain Accuracy:', train_accuracy)
print('Test Accuracy:', test_accuracy)
print('Train F1-Score:', train_f1)
print('Test F1-Score:', test_f1)

analyze_fit(train_accuracy, test_accuracy, train_f1, test_f1)


Confusion Matrix (Training Set):
[[  5   0   0   0   0   0   0   0   0   0   0]
 [  1  15   1   0   1   0   0   0   0   0   0]
 [  1   4  27   1   1   0   1   0   1   0   0]
 [  0   2   8  69   7   0   0   1   0   0   0]
 [  0   2   4  12 100   3   3   2   0   0   0]
 [  0   0   3  14  26  80   6   2   0   0   1]
 [  0   0   4  13  13  21  92  13   3   0   2]
 [  0   0   2   6   9  14  25  59   1   0   1]
 [  0   0   1   3   8  12  12   6  17   1   2]
 [  0   1   1   2   2   7   3   4   0   7   0]
 [  0   1   2   1   6   1  17   1   1   1  21]]

Confusion Matrix (Test Set):
[[ 0  1  0  0  1  0  0  0  0  0  0]
 [ 0  0  1  1  2  0  2  0  0  0  0]
 [ 0  3  4  4  3  0  2  1  0  0  0]
 [ 0  2  3 11 18  4  3  0  0  0  0]
 [ 0  3  4 12 20  3  5  3  2  0  1]
 [ 0  0  2  6 14 19 17  1  2  0  1]
 [ 0  0  1  5  6 10 28  7  2  0  2]
 [ 0  0  3  4  7  3 20 20  5  1  2]
 [ 0  0  0  0  3  2  7  8  2  0  0]
 [ 0  0  0  0  1  1  1  3  1  2  1]
 [ 0  1  0  0  3  2  2  2  0  1  3]]

Classification Report